//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technics
    {
        public int Inv_number { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public System.DateTime Purchase_date { get; set; }
        public int Price { get; set; }
        public int Room_number { get; set; }
    }
}
