//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Inv_number { get; set; }
        public int Unit_number { get; set; }
        public int ID__person { get; set; }
        public System.DateTime Transfer_date { get; set; }
    }
}
