//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int Unit_number { get; set; }
        public int ID_person { get; set; }
        public string Unit_name { get; set; }
        public string Full_name { get; set; }
        public string Short_name { get; set; }
    }
}
